### PR TITLE
Issue/1115

### LINKED ISSUE #1115: Know what would be awesome? A link to the github repo in the descriptions field of plugins.
image

In the description field (or maybe even in the actions box for manually uploaded plugins) have a link to the github repo visible, so you can quickly jump to it and see if there is a later version to update to.

### PR DESCRIPTION
**Pull request by hrajotia**
Fixes #1115 

Screenshot -
image

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by taylortom** [comment]
Nice one @hrajotia, this works well. 

What do we think about moving the link from the plugin name to the description field, and having the text as 'Visit plugin homepage' or similar? (with text localised in `en-application.json`) -- so that it's a bit more obvious what the link does before you click it.

**Comment by hrajotia** [comment]
@taylortom Thanks!
Do you mean something like below?
image

**Comment by taylortom** [comment]
@hrajotia that looks good to me :)

**Comment by taylortom** [comment]
+11

**Comment by lc-thomasberger** [comment]
+1

**Pull request merged**
