### PR TITLE
Issue/#596

### LINKED ISSUE #596: Blank text area input needs adding to scaffold
- Would enable custom text areas for importing wonderful things like LESS variables or custom theme settings

### PR DESCRIPTION
**Pull request by darylhedley**
fixes #596

### CODE REVIEW

**Comment by taylortom** [comment]
I think some of these changes my have been included in the latest merge. Can you try merging with develop first?

**Comment by darylhedley** [comment]
Yeah sorry meant to put the same note on this as this PR #595 
but also going to wait to pull these changes until the last PR has been merged in as I'd be duplicating the merge conflict fixes

**Comment by brian-learningpool** [comment]
@darylhedley, please abandon this PR and cherry pick commit 0938094 in a separate PR.

**Comment by darylhedley** [comment]
Closing this due to MOC (massive online conflict)
Reopened here
https://github.com/adaptlearning/adapt_authoring/pull/600

**Pull request closed without merging**
