### PR TITLE
Course force rebuild 

### PR DESCRIPTION
**Pull request by lc-thomasberger**
fixes #1584 #1497 

Based on https://github.com/adaptlearning/adapt_authoring/pull/1584 without the keyboard modifier.

image

### CODE REVIEW

**Comment by dancgray** [comment]
Works for me, good to surface this in the UI, but I think users will want it for publish and export. Would it be easier to have a toggle below the buttons with a rebuild option that would apply to all three and be stored as a preference?

**Comment by lc-thomasberger** [comment]
Does export and publish not always use a force rebuild? That's what I expected. If not a keyboard shortcut would probably the easiest solution to add force rebuild to all export types.

**Comment by dancgray** [comment]
@lc-thomasberger don't think it does. [Publish](https://github.com/adaptlearning/adapt_authoring/blob/release/0.5.1/plugins/output/adapt/publish.js#L131) is still checking for rebuild flag. Export always runs publish.

**Comment by taylortom** [comment]
Sorry to dive in late on this, but does anyone else think we should update publish & export to force a rebuild each time? (I also thought this happened already) - I don't think it makes sense to skip it with those functions.

**Comment by lc-thomasberger** [comment]
@taylortom that is probably what users expect.

Should we keep the toggle button or should we roll back to the "dropdown" style?

**Comment by lc-thomasberger** [comment]
@canstudios-nicolaw this would increase preview time as far as I am aware.

**Comment by canstudios-nicolaw** [comment]
@lc-thomasberger Ok, so just to be clear we are thinking of having publish and export force a rebuild every time, and then preview will have it's own force rebuild option in the UI?

**Comment by lc-thomasberger** [comment]
Exactly.
If you only change the json, preview will be faster without a force build. This is already handled by the Tool. If you would trigger a force rebuild you would need to change the theme or toggel the setting to create sourcemaps. This was a hack. The toggle button exposes this (useful) feature to the UI.

If you download or export a course, you would actually expect that the course is exported with the "latest" settings and plugin versions.

**Comment by canstudios-nicolaw** [comment]
:+1: Makes sense

**Comment by taylortom** [comment]
I hate to throw a spanner in the works, but did we mean to go back to the dropdown UI button? (@dancgray suggested the toggle back when it also affected publish/export). I really liked the DD button, and think it makes more sense from a UX perspective:
- Probably not something we should encourage too much, so good that it's partly hidden
- Feels a bit clunky to: turn on > publish > turn off (reminds me of those people who use caps lock instead of shift to capitalise a word...), I don't think this a feature that users will want to turn on/off globally

**Comment by lc-thomasberger** [comment]
I can bring the dropdown back.

**Comment by lc-thomasberger** [comment]
It does. It closes when preview is completed or when you click somewhere else. Except inside the drop-down element.

**Pull request merged**
