### PR TITLE
closing overlay using escape key

### LINKED ISSUE #741: Add escape key support for editing nested properties
When editing nested properties, such as the items on a narrative, the drawer/overlay it may sometimes be necessary to scroll to view the OK/Cancel buttons.  I propose adding support for the ESC key here to treat it as a click on Cancel.

### PR DESCRIPTION
**Pull request by hrajotia**
Fixes #741

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Comment by brian-learningpool** [comment]
I think you might have to add a `$(document).off()` call to the `close()` function in order to detach the listener?

**Comment by dennis-learningpool** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
