### PR TITLE
Resolves #1130, adds support for menu locking

### LINKED ISSUE #1130: Add support for menu locking
We need to support the `_isLocked` and `_lockType` properties as defined in this PR:
https://github.com/adaptlearning/adapt_framework/pull/1013

### PR DESCRIPTION
**Pull request by brian-learningpool**
This commit supports menu locking as part of the Adapt Framework v2.0.9 release.

### CODE REVIEW

**Comment by taylortom** [comment]
Looks good, +1

**Comment by dennis-learningpool** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1
though _isLocked supports a array of ID's. Would this string work `["co-1","co-2"]`?

**Comment by brian-learningpool** [comment]
Good catch, @lc-thomasberger.  I've just corrected that in the schema.

**Pull request merged**
