### PR TITLE
Resolves #690, adds support for Node.js 4.2.2 LTS

### LINKED ISSUE #690: Ensure compatibility with 4.2 node.js
Ensure compatibility with later versions, and implement a quarterly review.

### PR DESCRIPTION
**Pull request by brian-learningpool**
I had to update some dependencies due to deprecated functions.

There is an outstanding issue with a dependency on bson which gives the following warning:
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Thanks to @dancgray for starting this off.

**Comment by brian-learningpool** [comment]
This requires removing the `node_modules` folder and re-running: 
`npm install --production`.

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
Works for me. Tested using 0.10.33 and 4.2.2.
Can confirm @brian-learningpool's BSON warning,but doesn't seem to have any detrimental effect.

**Comment by dennis-learningpool** [comment]
Have tested works well.

+1

**Pull request merged**
