### PR TITLE
Fixes #618

### LINKED ISSUE #618: /api/content/schema breaks if extension properties.schema don't define a pluginLocations attribute

### PR DESCRIPTION
**Pull request by dennis-learningpool**

### CODE REVIEW

**Comment by taylortom** [comment]
+1, works for me

**Comment by dennis-learningpool** [comment]
I think that we need to put something more in place to ensure an uploaded plugin is not malformed, and to do this at the point of upload. 

I think we need a bit more discussion about hard and fast plugin requirements before we do that, though.

**Comment by finbartracey1** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
