### PR TITLE
Resolves #1027, corrects upgrade.js

### LINKED ISSUE #1027: Bug in upgrade.js
Running `node upgrade.js` fails, on `app.polyglot.t()`.

This is because the helper function is accessed before `app` had initialised.

### PR DESCRIPTION
**Pull request by brian-learningpool**
Call to the polyglot helper function should be deferred until the server has actually started.

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1
In terminal the "info: [09 Feb 2016 15:21:47 +00:00] Server started listening on port 5000" log gets inserted immediately after the "Would you like to continue?" prompt. 

Does not affect anything but I guess it might confuse some people.

**Comment by taylortom** [comment]
+1, also to @dancgray's comment.

There's quite a block of output when you first run the script, and it took me a few seconds to realise what I was supposed to do. Can we add a line or two of whitespace before the upgrade output?

**Comment by brian-learningpool** [comment]
I agree with @dancgray's comment.  I've noticed that a `skipVersionCheck` flag is passed in.  Do we have a similar flag to disable the logging during bootstrapping?

**Comment by dancgray** [comment]
@brian-learningpool cannot find one. I'm assuming we would not want to suppress all logging so will apply just to startServer. Shall i commit to issue/1027 branch?

**Comment by brian-learningpool** [comment]
Hi @dancgray, yeah, just commit on to his branch.

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
