### PR TITLE
Prototype theme editor

### PR DESCRIPTION
**Pull request by taylortom**
## Summary

Code for a theme editor I've developed. Could be used as a starting point for the open-source feature. Needs general tidying and tweaking to work with Learning Pool's plugins.

Summary of features:
- Replaces theme picker.
- Pulls in editable settings from the properties.schema associated with a theme.
  - The key value needs to map to the LESS variable value
  - The build process checks all .less files in the theme's less folder (but not sub-folders), and replaces any matches with the input values
- Allows the user to save selected settings as a 'preset' for the chosen theme, allowing them to be used in other courses.
- Adds a 'Clear colour' button to the ColorPicker to 'unset' a colour.
- Adds support for theme and menu to provide pluginLocations

## To test

1. Get a copy of the code in https://github.com/adaptlearning/adapt_authoring/tree/issue/1495
2. Get the latest node modules with `npm install`
3. Rebuild the front-end app with `grunt build`
4. That's it!

You'll then find the old theme picker has been replaced with a new section. I've set up a [test version of vanilla](https://github.com/taylortom/adapt-contrib-vanilla) which exposes a load of variables -- upload this using **Plugin management** as usual.

## Screenshots

See some screenshots below.

### Theme picker
screen shot 2017-02-05 at 22 44 45

### Theme settings
screen shot 2017-02-05 at 22 44 52

### Colour picker component
screen shot 2017-02-05 at 22 45 04

### Save preset button
screen shot 2017-02-05 at 22 48 26

### Create preset modal
screen shot 2017-02-05 at 22 48 02

### Manage presets modal
screen shot 2017-02-05 at 22 48 13

### CODE REVIEW

**Comment by letithappen** [comment]
Having no problem using theme editor to change colors, margins, etc using your vanilla or my  own theme after filling properties.schema as you did. Courses are previewing OK.
But i'm getting this error downloading the course:
image

**Comment by taylortom** [comment]
@letithappen your issue should be fixed now

**Comment by dancgray** [comment]
Looking fantastic. Can edit and preview changes using the new theme. 
Still getting an error on export source though: 
[theme-error.txt](https://github.com/adaptlearning/adapt_authoring/files/783649/theme-error.txt)

Should this be backward compatible with old themes? Only I'm getting a notify alert using the old theme "constructorFn is not a constructor". No errors on console or terminal.

**Comment by taylortom** [comment]
@dancgray yeah, should definitely allow you to select un-editable themes. Will have a look at that.

**Comment by taylortom** [comment]
@dancgray both of your issues should now be fixed :)

**Comment by dancgray** [comment]
👍  All fixed, I think that the course [schema](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/course/model.schema) will need the menu settings as well but we can add that with the menu settings changes.

If I was being pedantic the saved preset item should be selected in the dropdown list on return and the preset list should be updated if one is deleted, but really it's awesome as it is :)

**Comment by dancgray** [comment]
Sorry @taylortom just found something else, on the second download or export of a course I get an error, terminal output
[theme-settings-error.txt](https://github.com/adaptlearning/adapt_authoring/files/790896/theme-settings-error.txt)
 attached.

Could be my install of archiver module. Will try again tomorrow.

**Comment by tomgreenfield** [comment]
Superseded by #2209.

**Pull request closed without merging**
