### PR TITLE
Export for standalone development

### LINKED ISSUE #1013: Ability to export a course
Just the source initially...

### PR DESCRIPTION
**Pull request by taylortom**
Export course for development using the command line (i.e. grunt). Fixes #1013

#### Includes:
- Export button in project sidebar
- Packages all course data in a downloadable zip
- Auto-downloads zip to user computer
- **TODO** Converts hashed IDs to human-readable IDs

#### Doesn't include:
- Metadata for importing

### CODE REVIEW

**Comment by dancgray** [comment]
Works consistently for me (tested on a Mac). 

Would be good to have human readable id's. Also the grunt build tool refactor would allow for packaging relevant plugins only.

**Comment by brian-learningpool** [comment]
@taylortom, nice job, this works really well.  Some points:
- Possibly change the button label to 'Export source code' and change the icon to Font Awesome's `code` icon
- I think the display of this icon and the access to the endpoint should be restricted to a capability only assigned to the 'Super Admin' role initially

**Comment by brian-learningpool** [comment]
Also, in light of the impending drop of #1007 the `build` property will included in `config.json` could this be re-factored to address @dancgray's point about only bundling the relevant plugins only?

**Comment by taylortom** [comment]
@brian-learningpool, @dancgray the export [forces a build first](https://github.com/adaptlearning/adapt_authoring/blob/dev-export/plugins/output/adapt/index.js#L267-L269), so should work out-of-the-box. Will test this to make sure later.

Also need to merge in develop again by the looks of it.

**Comment by mediakitchen** [comment]
I have given this a test drive and it works really well.

Couple of minor issues that are probably just me being dumb.

After exporting my course I unzipped the folder and ran a "grunt build" from the folder root and it was aborted with the following:

**C:\Users\Paul\Downloads\my-new-course-export-2016-01-29-111513>grunt build
>> Local Npm module "grunt-bower-requirejs" not found. Is it installed?
>> Local Npm module "grunt-concurrent" not found. Is it installed?
>> Local Npm module "grunt-contrib-clean" not found. Is it installed?
>> Local Npm module "grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?
>> Local Npm module "grunt-contrib-copy" not found. Is it installed?
>> Local Npm module "grunt-contrib-handlebars" not found. Is it installed?
>> Local Npm module "grunt-contrib-less" not found. Is it installed?
>> Local Npm module "grunt-contrib-requirejs" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-jsonlint" not found. Is it installed?
>> Local Npm module "grunt-open" not found. Is it installed?
>> Local Npm module "grunt-requirejs-bundle" not found. Is it installed?
>> Local Npm module "adapt-grunt-tracking-ids" not found. Is it installed?
Warning: Task "requirejs:compile" not found. Use --force to continue.
Aborted due to warnings.**

So I ran "npm install" and after that "grunt build" worked fine so I was able to fire up my test course

**Comment by taylortom** [comment]
Update: still working on this, been having a headache with RegExes

**Comment by johnniezen** [comment]
How about http://fortawesome.github.io/Font-Awesome/icon/upload/? upload is sometimes used when exporting is meant. Just a thought.

**Comment by taylortom** [comment]
@johnniezen that might be the one to use for import, not sure the up arrow makes sense for export though. 
(have changed to use the code symbol for this dev release as per @brian-learningpool's suggestion).

**Comment by taylortom** [comment]
+1 for @brian-learningpool's changes, this should be good to go now!

**Comment by brian-learningpool** [comment]
+1

**Comment by paul-mediakitchen** [comment]
+1 (Tested on 2 devices - Win 10 Laptop and Win 10 Desktop both with Chrome)

Export source code works perfectly - nice work!!

**Comment by dancgray** [comment]
+1

**Pull request merged**
