### PR TITLE
lan-application.json files (EN/ES) updating and hard-coded strings detection

### PR DESCRIPTION
**Pull request by mariogalmonte**
app.assetmanagement is duplicated. Deleted the second one.

### CODE REVIEW

**Comment by canstudios-louisem** [comment]
related: #1715

**Comment by canstudios-louisem** [comment]
If this is going in we probably should update the grunt file so that it can be used

**Comment by mariogalmonte** [comment]
Indeed. For now it's a little tricky to translate. gruntfile line 10 must be modified:
`      src: ['routes/lang/es-application.json','frontend/src/plugins/**/lang/es.json'],`
and do grunt build. EN.json file will translate, so it isn't a clean change.

**Comment by canstudios-louisem** [comment]
I've quickly hacked together a patch for the grunt changes and language detection it should try and detect your browser language but it's not easy for me to test as a monolingual English speaker. Feel free to test it and commit it to your pr if it works.

[lang.txt](https://github.com/adaptlearning/adapt_authoring/files/1263113/lang.txt)

**Comment by tomgreenfield** [comment]
Would you mind changing the hardcoded text `"Plugin management"` to `Origin.l10n.t('app.pluginmanagement')` [here](
https://github.com/adaptlearning/adapt_authoring/blob/develop/frontend/src/modules/pluginManagement/index.js#L30) please?

Note: the unlocalised dashboard titles are fixed in https://github.com/adaptlearning/adapt_authoring/pull/1614.

**Comment by mariogalmonte** [comment]
@canstudios-louisem Must I add that code at the end of grunt file?

**Comment by mariogalmonte** [comment]
@canstudios-louisem Must I add that code at the end of grunt file?

**Comment by canstudios-louisem** [comment]
@mariogalmonte it's a git patch if you're not sure what to do with it don't worry I'll add another pr with it.

**Comment by mariogalmonte** [comment]
@canstudios-louisem I have tried to do the patch:
1. Rebuild develop version (original gruntfile ). sudo grunt build
2. Apply patch: sudo git apply --stat lang.patch
console shows:
```
.gitignore                |    1 +
 Gruntfile.js              |    9 +++++++++
 frontend/src/core/l10n.js |   26 +++++++++++++++++++++++++-
 3 files changed, 35 insertions(+), 1 deletion(-)
```
4. sudo node server.
But Adapt (ES Mozilla Firefox) is in English. Maybe I've done something bad?

**Comment by canstudios-louisem** [comment]
@mariogalmonte try a `grunt build` and then `node server` if not my language checking code may not be doing what I expected.

**Comment by mariogalmonte** [comment]
@canstudios-louisem . It doesn't work too. I've done:
`git apply --stat lang.patch`, `grunt build`, `node server`
Tested in Mozilla Firefox and Google Chrome. Ubuntu 14 LTS 64 bits

**Comment by canstudios-louisem** [comment]
Ok for now just carry on as you were with your change to the grunt file. Ill make this into a proper pr.

**Comment by mariogalmonte** [comment]
Ok. Thanks!

**Comment by taylortom** [comment]
Apologies, closing due to inactivity.

If there's still an appetite for these changes, please log an issue in the [v1](https://github.com/adapt-security/adapt-authoring) codebase.

**Pull request closed without merging**
