### PR TITLE
vagrant windows fix

### PR DESCRIPTION
**Pull request by lc-thomasberger**
solves: 
issue #1087
issue #1085 

have tested on 2 windows 7 machines

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1, thanks!

**Comment by brian-learningpool** [comment]
Tested on OSX Yosemite.  @lc-thomasberger, it might be worth merging the 32-bit branch into this PR too?

**Comment by lc-thomasberger** [comment]
Thanks for testing on OSX @brian-learningpool. I think we should stick with the 64-bit version for now and update the documentation that vt-x must be enabled on windows.

**Comment by dancgray** [comment]
+1  tested on default install of windows 8 64-bit

**Pull request merged**
