### PR TITLE
Fix shared courses query

### LINKED ISSUE #2294: Sorting broken on shared courses dashboard
## Expected Behaviour
By default, courses in the "My courses" and "Shared courses" area are sorted by the most recently edited dates. Users can also sort their courses alphabetically (A to Z; Z to A) in addition to their recently edited courses by clicking the corresponding sort buttons in the Dashboard. 
This behaviour and functionality is available in both the "My courses" and "Shared courses" area.

## Actual Behaviour
In the "Shared courses" area, the courses are sorted by date in reverse order i.e. more recently edited courses are towards the end of the list. Clicking the alphabetical and recent sort buttons refreshes the list but does not apply any changes.

## Steps to Reproduce
1. Navigate to Shared courses. Notice that courses are sorted in reverse date order.
1. Click the Alphabetical and Recent sort buttons. Notice that the list remains in the same order.

## Versions
  - Authoring Tool Version: 0.7.0

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #2294

### CODE REVIEW

**Comment by canstudios-nicolaw** [comment]
Z-A and most recent sort both work for me. A-Z gives me a 500 error with "You are not permitted to do that". Would you mind checking if this happens for you?

**Comment by taylortom** [comment]
Nope, not getting any network errors in my tests

**Comment by canstudios-nicolaw** [comment]
I've not forgotten this issue...I'm planning to delete all my shared courses and then create some more (with the different types of sharing) to see if one causes the issue to reappear. I'm wondering if I've got some dodgy course data left over from when I was working on the changes to behaviour when deleting shared courses.

**Comment by taylortom** [comment]
👍 no worries!

**Pull request merged**
