### PR TITLE
Tenant management v0.0.1

### PR DESCRIPTION
**Pull request by aniketdharia**

### CODE REVIEW

**Comment by taylortom** [comment]
Looks good (only looked over code).

I think we could do with opening a PR against develop once user management's gone in, not sure what this branch is used for.

**Comment by aniketdharia** [comment]
This is the branch tjat I have created today

**Comment by taylortom** [comment]
Yep sorry, updated my comment. Looks like it came from master though?

**Comment by aniketdharia** [comment]
@taylortom yes, should we have it from develop or master is fine?

**Pull request closed without merging**
