### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by taylortom**
Let me know if anything needs adding...

### CODE REVIEW

**Comment by taylortom** [comment]
Suggest possibly releasing this as 0.2.0, as fits semver better imo.

**Comment by brian-learningpool** [comment]
I agree about calling this release 0.2.0.

**Comment by brian-learningpool** [comment]
+1

**Comment by taylortom** [comment]
Have made a few changes to the formatting, and moved the common upgrade instructions to INSTALL.md

**Pull request merged**
