### PR TITLE
Update references to Spoor's main.html

### LINKED ISSUE #949: Replace references to spoor's main.html with index.html
This has been removed in the latest version of spoor.

Also looks like we need to fix a few hard-coded frontend references to main:
- [editorView](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/editor/global/views/editorView.js#L111)
- [sharedProjectView](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/project/views/sharedProjectView.js#L61)

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #949.

Appears that Origin adds the default outputmanager's Constants filename by default [if none is specified](https://github.com/adaptlearning/adapt_authoring/blob/master/routes/preview/index.js#L28).

### CODE REVIEW

**Comment by taylortom** [comment]
Have temporarily reverted the constants value to `main.html`. What is the best solution here?

**Comment by brian-learningpool** [comment]
I'm not sure right now but there probably shouldn't have been a breaking change introduced in a patch version of Spoor.

**Comment by taylortom** [comment]
Agreed, although this is something that needs to be fixed asap regardless, what with the refactored grunt stuff hopefully going in soon.

**Comment by dancgray** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
