### PR TITLE
Resolves #1060, removes the hasPermissions() check from retrieveAsset()

### LINKED ISSUE #1060: Performance issue with retrieveAsset()
The `retrieveAsset()` function does not require checking read permissions on every asset returned.  It's a given that the Course Creator role already has access to read all these assets.

### PR DESCRIPTION
**Pull request by brian-learningpool**
This check is not required as the Course Creator role has access to read all assets.

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
+1

**Comment by bell87** [comment]
+1

**Comment by taylortom** [comment]
Is there any need for a role (or the ability to create a role) without read access to assets (can't really think of any useful real-world examples, but thought I'd ask the question).

**Comment by brian-learningpool** [comment]
No, it's a fair point.  There is the 'Authenticated User' role which is pretty redundant now.  

I think roles and permissions are probably due a revisit.

**Comment by taylortom** [comment]
Fair enough. 
I can't think of a decent enough reason to lock down this function, so +1 (with the variables at the top of the function removed :smile:)

**Comment by ryangadams** [comment]
+1

**Pull request merged**
