### PR TITLE
 Rather large merge including fixes for:

### PR DESCRIPTION
**Pull request by dennis-learningpool**
ABU-218 - copy and paste moved to server
 ABU-237 - tidy up editor screens
 ABU-239 - reset forgotten password
 ABU-240 - first and last login for users
 ABU-337 - prefer environment configuration
 ABU-215 - tags don't autocomplete
 ABU-179 - remove hardcoded version from bower plugins
 ABU-231 - course visibility
 ABU-234 - insecure passport session data

 plus numerous other improvements

 Contributors:
 Brian Quinn
 Daryl Hedley
 Dennis Heaney
 Finbar Tracey
 Ryan Adams

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
NB: I suggest we don't merge this PR until the outstanding issue with adapt-contrib-spoor is fixed here:

https://github.com/adaptlearning/adapt-contrib-spoor/issues/53

Otherwise, users will have trouble previewing courses that don't use the spoor extension.

**Comment by oliverfoster** [comment]
So, original scan of the changes look good, can we have an overview of the changes made, additions, deviations, fixes etc on the call later? 466 files sounds like a lot of library style code.

**Comment by dancgray** [comment]
Looks good. Like the install method.

The following lines need "Learning Pool" text removed:

https://github.com/adaptlearning/adapt_authoring/blob/learningpool-merge/frontend/src/core/user/templates/login.hbs#L15

https://github.com/adaptlearning/adapt_authoring/blob/learningpool-merge/routes/lang/en.json#L68

https://github.com/adaptlearning/adapt_authoring/blob/learningpool-merge/routes/lang/en.json#L203

**Comment by dennis-learningpool** [comment]
@dancgray - good call. I'll update.

**Comment by dancgray** [comment]
I really like the typeform feedback (typeform is awesome). Is this included in the PR and if so will it be configurable? Could not find where this was configured, probably just need to look harder :)

**Comment by taylortom** [comment]
Looking really nice guys :)
Will hold off on +1 until I've had a chance to have a proper look

**Comment by dennis-learningpool** [comment]
I'm still working on the log of changes - will have that by the end of the day.

**Comment by oliverfoster** [comment]
Awesome, the phone call was a really good start, a rough change log would be fine I think.

**Comment by taylortom** [comment]
+1 (seems a bit pointless doing this due to the nature of the update, but anyway)

**Pull request merged**
