### PR TITLE
all the changes to the core .schema files from the framework v3.0.0 release

### PR DESCRIPTION
**Pull request by moloko**
see https://github.com/adaptlearning/adapt_framework/issues/1997

### CODE REVIEW

**Comment by taylortom** [comment]
Cheers for this @moloko 👍

**Comment by lc-thomasberger** [comment]
I think [this issue](https://github.com/adaptlearning/adapt_authoring/issues/1757) should be considered / fixed first.

**Comment by taylortom** [comment]
I don't think it makes sense to attempt #1757 before the server rewrite -- any solution we come up with is going to need a massive refactor of the database code

**Comment by taylortom** [comment]
@tomgreenfield where do we stand on this **post-v0.6.3**?

**Comment by tomgreenfield** [comment]
Schema now picked up from the framework.

**Pull request closed without merging**
