### PR TITLE
Adds custom LESS to exports.

### LINKED ISSUE #1439: No custom LESS file is generated during source code export

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #1439.

File is written to: `src/theme/THEME_NAME/less/zzzzz.less`. File name comes from outputmanager.less `Constants.Filenames.CustomStyle`.

I also took the liberty of moving out the different functions into separate files to match importsource (should make maintenance a bit easier).

### CODE REVIEW

**Comment by lc-thomasberger** [comment]
When I export a course, I do get an error. I also get this error with no custom styling.

```
info: [26 Sep 2018 13:43:31 +02:00] Retrieving JSON
info: [26 Sep 2018 13:43:31 +02:00] All assets processed
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at D:\AT-Project\at_repo\adapt_authoring\plugins\output\adapt\export.js:92:34
    at D:\AT-Project\at_repo\adapt_authoring\plugins\content\config\index.js:194:22
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1140:9
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1064:13)
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:969:16
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1137:13
    at D:\AT-Project\at_repo\adapt_authoring\plugins\content\config\index.js:187:22
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1135:9
    at eachOfArrayLike (D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1069:9)
    at eachOf (D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1117:5)
    at _asyncMap (D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1133:5)
    at Object.map (D:\AT-Project\at_repo\adapt_authoring\node_modules\async\dist\async.js:1122:16)
    at D:\AT-Project\at_repo\adapt_authoring\plugins\content\config\index.js:176:19
    at D:\AT-Project\at_repo\adapt_authoring\node_modules\mongoose\lib\model.js:4485:16
    at (anonymous function).call (D:\AT-Project\at_repo\adapt_authoring\node_modules\mongoose\lib\query.js:3613:7)
    at process.nextTick (D:\AT-Project\at_repo\adapt_authoring\node_modules\mongoose\lib\helpers\query\completeMany.js:35:39)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

It seems that `docs[0]._theme` is `undefined`. https://github.com/adaptlearning/adapt_authoring/blob/issue/1439/plugins/output/adapt/export.js#L92

Custom themes are saved as folders with the user's id. There is not reference to a theme in course or config collection?
To me it would make more sense that the custom theme name is generated using the course id that contains the custom styling. We might also use the content of the custom styling to create a unique hash, as we do with assets.

**Comment by taylortom** [comment]
The `_theme` value is set [when the theme is changed](https://github.com/adaptlearning/adapt_authoring/blob/issue/1439/plugins/content/theme/index.js#L196), so you'll get this error when you've got a course that hasn't had a specific theme set yet.

The idea with the folder location is that the custom less file is dumped out in the theme folder (i.e. `adapt-contrib-vanilla` etc.) as the custom theme folder (hashed) isn't included in the export.

**Comment by lc-thomasberger** [comment]
Thanks for your reply @taylortom . If I select a theme it works.
I think we should either make sure the default theme is selected or show an error to the if no theme is selected.

**Comment by lc-thomasberger** [comment]
This feels a bit ugly but could be fine until the big refactor / rewrite.

All default plugins are loaded from [adapt.json](https://github.com/adaptlearning/adapt_framework/blob/master/adapt.json) located in the Framework. This could possible be different depending on the specified Framework gir src. So we might read this file and look for the first plugin that is from type [theme](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/bower.json#L8) and use this as a default. This function could be located in Frameworkhelpers. We can fallback to `adapt-contrib-vanilla`.

**Comment by taylortom** [comment]
I think ultimately, we should be getting the user to select the theme each time a new course is created so that this becomes a non-issue.

In this case, I'm happy with either solution. If we go for something dynamic, we can also remove the code in outputmanager.js: [L64-L67](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/outputmanager.js#L64-L67) & [L305-L310](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/outputmanager.js#L305-L310).

**Comment by lc-thomasberger** [comment]
Thanks Tom for pointing to the code snippets.

I think we should remove the defaults from the default theme and menu from the backend and force users to select a theme and menu.

**Pull request merged**
