### PR TITLE
Fix asset management pagination

### PR DESCRIPTION
**Pull request by taylortom**
Also gave the files I touched a bit of a tidy.

### CODE REVIEW

**Comment by dancgray** [comment]
@taylortom for me the filters are not working. Tested with a very large collection, no errors returned.

**Comment by taylortom** [comment]
Ok cheers, will have a lookie

**Comment by lc-thomasberger** [comment]
Pagination works for me, but filters are broken as well. Tested with 38 elements inside the assets collection.

**Comment by lc-thomasberger** [comment]
edit seems to be a bit broken as well.

**Comment by taylortom** [comment]
Thanks @lc-thomasberger, your changes work for me! :)

**Comment by dancgray** [comment]
The asset picker modal that you get when choosing an asset for a plugin does not initially show all assets. Resizing causes all assets to render.

Tag and search filter works though :)

**Comment by taylortom** [comment]
Thanks Dan, those should be sorted now

**Comment by taylortom** [comment]
Just fixed another issue with the modal's scrollbar being shown when it shouldn't (the asset management modal has its own scrollbar)

**Comment by dancgray** [comment]
@taylortom works for me. Does not seem to be refreshing the collection of assets if you upload through the modal window though. I'm sure it used to highlight the image you just uploaded.

**Comment by taylortom** [comment]
@canstudios-louisem, @dancgray @lc-thomasberger This is ready to test again :)

**Pull request merged**
