### PR TITLE
Publish re work

### PR DESCRIPTION
**Pull request by ryankilf**
This resolves issue #966 ( https://github.com/adaptlearning/adapt_authoring/issues/966 )

I've also snuck in a spelling fix.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by ryangadams** [comment]
This should be targeting develop not publish-re-work?

**Comment by ryangadams** [comment]
Doing a search suggests there's a method on the OutputPlugin interface called publish. Does that need to be renamed? If so, any implementations will need to be updated too (which I think is only plugins/publish/Adapt at this point).  Additionally, routes/lang/en-application.json has some app.publish-like strings which might need updated.

**Pull request closed without merging**
