### PR TITLE
Spectrum ColorPicker 

### LINKED ISSUE #2014: Replace colour picker widget with something better supported
Possibilities:
- [CSS Script (basic)](https://www.cssscript.com/demo/color-picker-component-pickr/)
- [CSS Script (alpha)](https://www.cssscript.com/demo/color-picker-alpha-selection/)
- [Spectrum](http://bgrins.github.io/spectrum/)
- [Jscolor](http://jscolor.com/)

### PR DESCRIPTION
**Pull request by lc-thomasberger**
Replace ColorPicker with [Spectrum](http://bgrins.github.io/spectrum/) library.

It is leaner and more powerful and also easier to use.
I have added the config that made the most sense to me. Please let me know if you would like a feature or if a feature should be removed.
In future versions I would like to have course specific color swatches that could then be used to populate Spectrum's palette.

Fixes #2014 

## Checklist

Below is a checklist of the key things that the core team will be looking for when reviewing your PR. Please check off as many of these as you can prior to submitting the PR, but don't worry if you can't do all of them, the core team are here to help!

- [x] I have read the [CONTRIBUTING](https://github.com/adaptlearning/adapt_authoring/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have checked that the code compiles correctly
- [ ] I have checked that unit test suite passes locally with my changes
- [ ] I have added new tests that cover my changes (where appropriate)
- [x] I have added documentation (where appropriate)
- [x] Any dependent changes have already been merged

## Next steps

The core team will be automatically notified of your changes, but also feel free to bring it to our attention via the [gitter.im channel](https://gitter.im/adaptlearning/adapt_authoring).

### CODE REVIEW

**Comment by taylortom** [comment]
Are we happy this does everything we need? The last release was Aug 2016.

**Comment by taylortom** [comment]
I've experimented a bit with the default styling to make the picker a bit more modern-looking. Any feedback, let me know. Otherwise, happy to push these to the branch.

You can see a diff of the changes [here.](https://github.com/adaptlearning/adapt_authoring/compare/issue/2014...issue/2014-2)

***
## Before
screen shot 2018-07-23 at 17 43 37


## After
screen shot 2018-07-23 at 17 29 17

**Comment by lc-thomasberger** [comment]
@taylortom I do like the larger swatches, but I do miss the buttons. The trah-icon is needed to remove a selected Color. Also The Cross to cancel makes sense to me and improves usability of the color picker.

**Comment by taylortom** [comment]
I'm happy to add the buttons back in, my thinking was this:
- Generally make the UI look more cluttered
- We don't have 'undo' actions on other input fields
- The apply/tick isn't needed as just picking a colour has the same effect
- I wasn't sold on the need/usefulness of the trash button as we now have the revert button to restore the schema default

**Comment by taylortom** [comment]
As a side-note, we should probably also switch to the british english 'colour' when this goes in.

**Comment by taylortom** [comment]
Superseded by #2032.

**Pull request closed without merging**
