### PR TITLE
fix scroll-position in pageEditor

### LINKED ISSUE #1814: scroll position in page editor
## Expected Behaviour
scroll position in page editor should be persistent 

## Actual Behaviour
When you edit an element in the page editor and return back, scrollTop is set to 0.

## Steps to Reproduce
1. create course
2. add enough components so that scrollbars appear
3. edit a component
4. return to page editor

## Versions
  - Authoring Tool Version: 0.4.0
  - Operating System: All
  - Browser: All

### PR DESCRIPTION
**Pull request by lc-thomasberger**
fixes #1814 

css transitions not fired when articles are collapsed (display-none).
Use velocity to animate the blocks and trigger the events to detect that all children are ready.

### CODE REVIEW

**Comment by taylortom** [comment]
Doesn't seem to be restoring the position for me

**Comment by taylortom** [comment]
Changing the scroll div from `.contentPane` to `.editor-view` should fix the problem

**Comment by taylortom** [comment]
@tomgreenfield haven't touched the velocity code you commented on, as your suggested fix stopped the inner block content from showing, and wasn't sure of its initial intent.

**Comment by tomgreenfield** [comment]
Sorry @taylortom, that's a typo – I meant use a `begin` function. The inner context text doesn't animate properly without this amend.

**Comment by taylortom** [comment]
Should be good to go

**Comment by lc-thomasberger** [comment]
@taylortom have you tested this PR without https://github.com/adaptlearning/adapt_authoring/pull/1999 being merged?
`.contentPane` should be the scrollcontainer. If I test this PR (with the latest changes from develop) the scroll position is not restored. If I change it to `.contentPane` it works.

**Comment by taylortom** [comment]
Cool, no, had no idea it was dependent on anything else.

**Pull request merged**
