### PR TITLE
copy / move editor array item

### PR DESCRIPTION
**Pull request by lc-thomasberger**

### CODE REVIEW

**Comment by taylortom** [comment]
Did you have a look at the sortable plugin linked to in the [original issue](https://github.com/adaptlearning/adapt_authoring/issues/1430)?

**Comment by lc-thomasberger** [comment]
No, I have not seen this. Looks good, will have to test it.

**Comment by taylortom** [comment]
Yeah, good point. I'll look into how easy it is to do this with jQuery UI.

**Comment by taylortom** [comment]
Have done a prototype [here](https://github.com/adaptlearning/adapt_authoring/compare/feature/scaffoldRefactor...feature/copyMoveItem-jqueryui)

**Comment by tomgreenfield** [comment]
Love the draggable prototype, @taylortom. Default values, reset button and printing of nested objects need close attention.

**Comment by lc-thomasberger** [comment]
@taylortom yes this is very nice. I made some styling tweaks, added a drop-placeholder and styled the dragged element a bit.

itemsdnd

**Comment by taylortom** [comment]
Thanks for that, looks really nice :) Happy with whatever makes it easiest for you.

**Comment by lc-thomasberger** [comment]
Superseded by https://github.com/adaptlearning/adapt_authoring/pull/2034

**Pull request closed without merging**
