### PR TITLE
sequential locking on sub menus

### PR DESCRIPTION
**Pull request by lc-thomasberger**
uses `editorAttrs` to customize the behavior of the inputType.

### CODE REVIEW

**Comment by taylortom** [comment]
Does this supersede https://github.com/adaptlearning/adapt_authoring/pull/1647?

**Comment by lc-thomasberger** [comment]
If you are happy with the `editorAttr` then it does.

**Comment by tomgreenfield** [comment]
For a future release, suggest adding a `data-adapt-type` or similar to the parent view, by checking `this.model.get('_type')` [here](https://github.com/adaptlearning/adapt_authoring/blob/develop/frontend/src/modules/editor/global/views/editorOriginView.js#L14-L19). Could then maybe hide / grey out fields with classes.

**Comment by lc-thomasberger** [comment]
@tomgreenfield yes we need some sort of standardized way about how to deal with customizing editors.
Showing editors only for certain types, as well as collapsing editors (= reduces page size) would be great for the start.
I think we should do this already at the start and maybe defer this PR to the next release.

I would not grey out items. If a attribute is not available for a certain type, it should not be displayed at all.

**Pull request closed without merging**
