### PR TITLE
Upgrade Backbone Forms; move overrides out

### LINKED ISSUE #1544: Upgrade Backbone Forms
- Upgrade Backbone Forms to latest master code
- Move any amendments to scaffoldOverrides.js

### PR DESCRIPTION
**Pull request by tomgreenfield**
Resolves #1544.

### CODE REVIEW

**Comment by taylortom** [comment]
Not brave enough to go through this properly right now, but had a look at the diff, and looks good 👍

**Comment by taylortom** [comment]
Can I suggest we rename `scaffoldOverrides` to `backboneFormOverrides` (or something more succinct)? `scaffoldOverrides` isn't really representative of its purpose.

**Comment by tomgreenfield** [comment]
@taylortom, could we get these changes into the big bug fix?

**Comment by taylortom** [comment]
Yeah, think we should. If you get some time, could you have a look at how these merge into the bug fix branch?

**Comment by tomgreenfield** [comment]
Closing this PR in favour of a new one into [thebigbugfix](https://github.com/adaptlearning/adapt_authoring/tree/thebigbugfix/refactor).

**Pull request closed without merging**
