### PR TITLE
Upgrade.js detect framework v1.1.5.

### LINKED ISSUE #775: Upgrade.js misses framework v1.1.5 available - does not upgrade.
screen shot 2015-08-11 at 12 24 46

### PR DESCRIPTION
**Pull request by jdtoy**
Added missing async.detectSeries callback, fixes #775.

### CODE REVIEW

**Comment by jdtoy** [comment]
Failing CI seems unrelated.

**Comment by dennis-learningpool** [comment]
This change looks good (don't worry about the failing CI - we have another issue open to address that).

I can't test this at the moment, but will do in the morning. I can't imagine it'll cause any problems, though, so:

+1

**Comment by darylhedley** [comment]
+1 - works for me

**Comment by nilssanderson** [comment]
+1

**Pull request merged**
