### PR TITLE
Add displayTitle to course schema

### LINKED ISSUE #848: Course now requires a field for Display Title
Version 2.x of the framework requires this.  This should be implemented like the display titles in articles, blocks and components.

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #848

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
+1

**Comment by taylortom** [comment]
Have set `required` to false to match other occurrences

**Comment by dancgray** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
