### PR TITLE
Update: From ckeditor4 4.17.0 to ckeditor5 42.0.0 (fixes #2772)

### LINKED ISSUE #2772: CKEditor started to show a warning - Needs a quick replacement
## Expected Behaviour
CKEditor which is used to edit the Body in almost all entities started to show warning message.

"This CKEditor 4.16.1 version is not secure. Consider upgrading to the latest one 4.24.0-lts"

image

## Actual Behaviour
There shouldn't be a warning and editor should work as expected.

## Steps to Reproduce
1. Open any component and focus on Editor view of body property

Note:
A quick way to suppress the warning is by adding `versionCheck:false` in `frontend/src/modules/scaffold/backboneFormsOverrides.js` line 71.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #2772

Updated from ckeditor4 4.17.0 to ckeditor5 42.0.0 

image

### CODE REVIEW

**Review by taylortom — DISMISSED** [review]
Works well for me. 

Had a play with removing features, but was more fiddly than expected and not sure it's worth the effort.

**Comment by oliverfoster** [comment]
Can you retest with the ones I've commented out and then remove them if not necessary please?

This is the list of plugins and what they do, I don't know if any of these features are things which you're expecting to keep in the transition. Especially the image embedding and editing:

https://ckeditor.com/docs/ckeditor5/latest/api/module_image_autoimage-AutoImage.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_editorui_accessibilityhelp_accessibilityhelp-AccessibilityHelp.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_ckbox_ckbox-CKBox.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_ckbox_ckboximageedit-CKBoxImageEdit.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_cloud-services_cloudservices-CloudServices.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_heading_heading-Heading.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_horizontal-line_horizontalline-HorizontalLine.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_html-embed_htmlembed-HtmlEmbed.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageblock-ImageBlock.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption-ImageCaption.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageinline-ImageInline.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageinsert-ImageInsert.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageinsertviaurl-ImageInsertViaUrl.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageresize-ImageResize.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagestyle-ImageStyle.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagetextalternative-ImageTextAlternative.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagetoolbar-ImageToolbar.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload-ImageUpload.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_link_linkimage-LinkImage.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbed.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_pictureediting-PictureEditing.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_list_todolist-TodoList.html

**Comment by taylortom** [comment]
Well that's stumped me - I got missing plugin errors when I tried that earlier, must've not rebuilt the UI correctly or something.

Have updated.

**Comment by oliverfoster** [comment]
Looks good now 👍

**Review by taylortom — DISMISSED** [review]
### Approved :fire:

_Note to other reviewers: I've also made some very minor changes_

**Comment by canstudios-nicolaw** [comment]
@oliverfoster @taylortom Hi both, thanks for these changes

On the CKEditor site, they have a section about upgrading from 4 to 5. 

https://ckeditor.com/blog/upgrade-ckeditor-4-to-5/#step-by-step-to-upgrade-your-editor-from-ckeditor-4-to-ckeditor-5

This site mentions the risk of moving data from 4 to 5 and says that "Because CKEditor 5 utilizes an MVC architecture with a custom data model (as compared to CKEditor 4 HTML-oriented architecture), there may be some data incompatibility issues.".

Have you been able to do much testing with course content? Do you have any concerns that upgrading to CKEditor 5 might cause some data loss in existing courses within the AT?

**Comment by oliverfoster** [comment]
> @oliverfoster @taylortom Hi both, thanks for these changes
> 
> On the CKEditor site, they have a section about upgrading from 4 to 5.
> 
> https://ckeditor.com/blog/upgrade-ckeditor-4-to-5/#step-by-step-to-upgrade-your-editor-from-ckeditor-4-to-ckeditor-5
> 
> This site mentions the risk of moving data from 4 to 5 and says that "Because CKEditor 5 utilizes an MVC architecture with a custom data model (as compared to CKEditor 4 HTML-oriented architecture), there may be some data incompatibility issues.".
> 
> Have you been able to do much testing with course content? Do you have any concerns that upgrading to CKEditor 5 might cause some data loss in existing courses within the AT?

I think that's part of the paid server-side suite they offer. There's a series of collaboration features which have a server-side component you can license from CKEditor5 https://ckeditor.com/ckeditor-5/features/ . We don't use any of there server side features, only use the text editor code which reads and writes data in the browser from the data we give it. There is no need for migration steps 2-4.

**Comment by tomgross** [comment]
Any date when this will be merged? Anything I can help to get this out?

**Comment by simondate** [comment]
I've been using this version of CK Editor with a client (v5 42.0.0) and they've noticed that by default, they can't write classes inline in text as when they press save in the Authoring Tool it doesn't get saved. It's also added `_blank` to links so they open up in new tabs.

I think by default behaviour should match exactly v4 CKeditor

**Comment by taylortom** [comment]
Hi all, this one's been a bit quiet recently - are we still happy with updating CKE?

Thanks for the approval @simondate - I'm assuming you've been using this one already

**Comment by oliverfoster** [comment]
i'm happy if simon is happy

**Review by taylortom — APPROVED** [review]
:eyes:

**Pull request merged**
